Feature/attendance
jdpasternak/activently pull request #71
Opened 2022-02-19 18:01 UTC by Naomilounsbury

got the attend button working
note: I added a return in api user-routes login because the session storage wasnt working properly.

2022-02-20 06:39 UTC, jdpasternak requested changes
Various changes to be made. Please review my comments. Feel free to slack me with questions

2022-02-20 06:39 UTC, jdpasternak commented on controllers/api/activity-routes.js
> +    .then(() => {
We don't render HTML from an API route. What is the purpose of this?

2022-02-20 06:39 UTC, jdpasternak commented on controllers/api/user-routes.js
> +        return res.json({ user: dbUserData, message: "You are now logged in!" });
Should not return anything here. `res.json()` is used to provide the data back to the client and doesn't return anything useful

2022-02-20 06:39 UTC, jdpasternak commented on controllers/homepage-routes.js
> +      console.log(dbActivityData.get({ plain: true }), "HEY HO");
What is the purpose of this?

2022-02-20 06:39 UTC, jdpasternak commented on controllers/homepage-routes.js
> +        count: dbActivityData.attending.length,
This is called something different elsewhere. We should stick to same naming of all model attributes.  Refer to `activity-routes.js` lines 95-98 for an example of how to get this data and how to return it as part of the rest of the body

2022-02-20 06:39 UTC, jdpasternak commented on public/javascript/attend.js
> +  const userId = window.sessionStorage.user_id;
You already have the `user_id` information retrieved from `req.session`.  This code is unnecessary

2022-02-20 06:39 UTC, jdpasternak commented on views/activity.handlebars
> +                  <span class="">{{count}} attending</span>
what this key's name is changed in the `homepage-routes`, this `count` should change as well

2022-02-20 21:43 UTC, Naomilounsbury commented on controllers/api/activity-routes.js
> +    .then(() => {
I'll move it to the homeroutes

2022-02-20 21:43 UTC, Naomilounsbury commented on controllers/api/user-routes.js
> +        return res.json({ user: dbUserData, message: "You are now logged in!" });
https://stackoverflow.com/questions/54881840/express-session-doesnt-save

2022-02-20 21:44 UTC, Naomilounsbury commented on controllers/homepage-routes.js
> +      console.log(dbActivityData.get({ plain: true }), "HEY HO");
Ill delete that, it was to make sure that one was rendering not the other

2022-02-20 21:45 UTC, Naomilounsbury commented on controllers/homepage-routes.js
> +        count: dbActivityData.attending.length,
fine but this way is also functional

2022-02-20 21:47 UTC, Naomilounsbury commented on views/activity.handlebars
> +                  <span class="">{{count}} attending</span>
fine

2022-02-20 21:58 UTC, jdpasternak commented on controllers/api/user-routes.js
> +        return res.json({ user: dbUserData, message: "You are now logged in!" });
This doesn't save the session.  It works without this line

2022-02-20 22:01 UTC, jdpasternak commented on controllers/api/activity-routes.js
> +    .then(() => {
If you're writing an API endpoint, it should stay in the API controllers.  What I meant was that this route should strictly response with JSON data

2022-02-20 22:03 UTC, jdpasternak commented on controllers/homepage-routes.js
> +        count: dbActivityData.attending.length,
You're right. I'm referring to the consistency in the code.  We want to try to maintain consistency even with components that are not directly related.

2022-02-20 22:14 UTC, Naomilounsbury commented on public/javascript/attend.js
> +  const userId = window.sessionStorage.user_id;
ok deleted

2022-02-20 23:13 UTC, Naomilounsbury commented on controllers/api/activity-routes.js
> +    .then(() => {
So it wont refresh with just the json data. re rendering the page refreshes the page and shows the data whenever someone clicks attend

2022-02-20 23:21 UTC, jdpasternak commented on controllers/homepage-routes.js
> +      console.log(dbActivityData.get({ plain: true }), "HEY HO");
This hasn't been removed

2022-02-20 23:23 UTC, jdpasternak commented on controllers/api/user-routes.js
> +        return res.json({ user: dbUserData, message: "You are now logged in!" });
I just tested this and it works without needing `return`. Please remove this before the PR is merged

2022-02-20 23:25 UTC, jdpasternak requested changes

2022-02-20 23:25 UTC, jdpasternak commented on controllers/api/activity-routes.js
> +    .then(() => {
API routes do not render HTML. They should only response with JSON, XML, or some other structured data.  The refreshing of the page should be done on the front end.  After a `fetch` request to `/api/activities/attend`, use `location.reload()` to refresh the page

2022-02-21 00:42 UTC, jdpasternak approved these changes

2022-02-21 01:07 UTC, merged